#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo 'Error: Missing directory argument'
    exit 0
fi

path=$1

for file in "$path"*; do
    base_name=$(basename "$file")
    new_name="$path""$RANDOM"-"$base_name"
    mv "$file" "$new_name"
done
